development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wuk_development
  pool: 5 
  username: kdtm
  password: kdtm783640 
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wuk_test
  pool: 5
  username: kdtm
  password: kdtm783640
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: wuk_production
  pool: 5
  username: root
  password: 
  host: localhost
